name: practi_horas_app
description: "Aplicación móvil para el control inteligente de horas de prácticas pre-profesionales."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.3
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  animate_do: ^3.3.4
  share_plus: ^9.0.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  pdf: ^3.10.8
  tutorial_coach_mark: ^1.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4F46E5"
  adaptive_icon_foreground: "assets/logo.png"